@startuml
'https://plantuml.com/sequence-diagram

autonumber

MCP_UI_Client -> MCP_Server: Sends the prompt "Book a meeting at 9AM on 21st Oct 2025 for an appointment"
MCP_Server --> LLM: Sends the prompt and ask for decision
LLM --> MCP_Server: Responds with the decision
MCP_Server --> CalendarTool: Depending upon LLM's decision server calls tool
CalendarTool --> MCP_Server: Returns the response
MCP_Server --> MCP_UI_Client: Returns the response

@enduml